export const COUNTRIES_GETALL_REQUEST = 'COUNTRIES_GETALL_REQUEST'
export const COUNTRIES_GETALL_SUCCESS = 'COUNTRIES_GETALL_SUCCESS'
export const COUNTRIES_GETALL_FAILURE = 'COUNTRIES_GETALL_FAILURE'