export const COUNTRIES_GETALL_REQUEST = 'COUNTRIES_GETALL_REQUEST'
export const COUNTRIES_GETALL_SUCCESS = 'COUNTRIES_GETALL_SUCCESS'
export const COUNTRIES_GETALL_FAILURE = 'COUNTRIES_GETALL_FAILURE'

export const COMMENTS_GETALL_REQUEST = 'COMMENTS_GETALL_REQUEST'
export const COMMENTS_GETALL_SUCCESS = 'COMMENTS_GETALL_SUCCESS'
export const COMMENTS_GETALL_FAILURE = 'COMMENTS_GETALL_FAILURE'

export const COMMENTS_UPDATE = 'COMMENTS_UPDATE'
